module.exports = {
  apps: [
    {
      name: 'leadflow-bot',
      script: 'npx',
      args: 'tsx src/bot/telegram-runner.ts',
      cwd: './',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      exp_backoff_restart_delay: 100,
      env: {
        NODE_ENV: 'production',
        AUTO_PIPELINE_ENABLED: '1',
        SCRAPE_ECO_MODE: '1',
        SCRAPE_QUERY_CACHE_HOURS: '24',
        DAILY_LEAD_CAP: '500',
        DAILY_APIFY_BUDGET_USD: '5.00',
        AUTO_PIPELINE_TARGET_WEBS: '15',
        AUTO_PIPELINE_MAX_COMBOS: '6',
      },
      error_file: 'logs/bot-error.log',
      out_file: 'logs/bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'leadflow-web',
      script: 'npx',
      args: 'next start -p 3000',
      cwd: './',
      watch: false,
      autorestart: true,
      max_restarts: 5,
      restart_delay: 5000,
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
      },
      error_file: 'logs/web-error.log',
      out_file: 'logs/web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
